# Generated by Django 4.1.2 on 2022-10-28 18:17

import core.encryption
import core.models.game
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    core.encryption.BinaryEncryptedField(
                        editable=True, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    core.encryption.TextEncryptedField(
                        editable=True, verbose_name="description"
                    ),
                ),
                (
                    "price",
                    core.encryption.DecimalEncryptedField(
                        decimal_places=2,
                        editable=True,
                        max_digits=4,
                        verbose_name="price",
                    ),
                ),
                (
                    "cover",
                    core.encryption.ImageEncryptedField(
                        default="default/cover.png",
                        upload_to=core.models.game.path_game_cover,
                        verbose_name="cover",
                    ),
                ),
                (
                    "slug",
                    core.encryption.SlugEncryptedField(
                        unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "games",
                    models.ManyToManyField(
                        blank=True, to="core.game", verbose_name="games"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
