# Generated by Django 4.1.3 on 2022-11-13 16:18

import core.models.game
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encryption.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", encryption.fields.CharEncryptedField(verbose_name="name")),
                (
                    "description",
                    encryption.fields.TextEncryptedField(verbose_name="description"),
                ),
                (
                    "price",
                    encryption.fields.DecimalEncryptedField(
                        decimal_places=2, max_digits=4, verbose_name="price"
                    ),
                ),
                (
                    "cover",
                    encryption.fields.ImageEncryptedField(
                        default="default/cover.png",
                        upload_to=core.models.game.path_game_cover,
                        verbose_name="cover",
                    ),
                ),
                (
                    "slug",
                    encryption.fields.SlugEncryptedField(
                        unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "modified",
                    encryption.fields.DateTimeEncryptedField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "created",
                    encryption.fields.DateTimeEncryptedField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "games",
                    models.ManyToManyField(
                        blank=True, to="core.game", verbose_name="games"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
