# Generated by Django 4.1 on 2022-08-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_orderdetail_paymentdetail_orderitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="games",
            field=models.ManyToManyField(
                blank=True, to="core.game", verbose_name="games"
            ),
        ),
    ]
