# Generated by Django 4.1.3 on 2022-11-13 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encryption.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    encryption.fields.DateTimeEncryptedField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "created",
                    encryption.fields.DateTimeEncryptedField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    encryption.fields.CharEncryptedField(verbose_name="order id"),
                ),
                (
                    "amount",
                    encryption.fields.DecimalEncryptedField(
                        decimal_places=2, max_digits=6, verbose_name="amount"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    encryption.fields.DateTimeEncryptedField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "created",
                    encryption.fields.DateTimeEncryptedField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.game",
                        verbose_name="game",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checkout.orderdetail",
                        verbose_name="order detail",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="checkout.paymentdetail",
                verbose_name="payment",
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
